#####################################################################
# Automatically generated by qtpromaker
#####################################################################

TARGET = pix2ascii

OBJECTS_DIR = ./bin/objects
DESTDIR = ./bin

SOURCES *= \
    src/Main.cpp
